name: Deploy Services

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push-ingestion:
    name: Build & Push Ingestion Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Ingestion Docker Image
        run: |
          docker build -t supply-conduit-ingestion:latest services/ingestion
